[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pylint.master]
jobs = 0

[tool.pylint.format]
max-line-length = 120
