name: lint

on: [push]


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Check style with black
        run: |
          black --check pdfhstack.py
      - name: Check imports with isort
        run: |
          isort --check pdfhstack.py
      - name: Lint with pylint
        run: |
          pylint pdfhstack.py